spring:
  application:
    name: hi-spring-cloud-eureka

server:
  port: 8762

eureka:
  client:
    service-url:
      register-With-Eureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka