spring:
  application:
    name: hi-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/course/**
      serviceId: hi-spring-cloud-course
    api-b:
      path: /api/member/**
      serviceId: hi-spring-cloud-member
